### ISSUE TITLE
Doesn't Work On 0.8.8

### ISSUE THREAD

**Issue by PhluXx1** [theripper93/ropes#1]
Hi this module doesn't work on Foundry 0.8.8 on Win10 64bit. I've also updated the module to 0.4.1 and it still doesn't work. 

I've disabled all modules and only enabled Ropes & Teathers and it's dependency but it still doesn't work.

I drag the relevant macros into the hotbar and clicked Start Rope then selected tokens and clicked Add to Rope but nothing happens.

I'm not the only one experiencing this issue please see the Reddit comments below:
https://www.reddit.com/r/FoundryVTT/comments/oo6wj4/ropes_tethers_create_ropes_and_tethers_between/h65kswq/

**Comment by theripper93** [comment]
ye i've heard that ropes has issue, i'll revisit it at some point but you'll have to wait a bit, in the mean time you can try the purge ropes macro and see if that helps
